version: '3.8'
services:
  nest_server:
    container_name: nest_graphql_server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    networks:
      - nest_graphql_network
    
  prisma:
    image: prismagraphql/prisma:latest
    ports:
      - '4466:4466'
    depends_on:
      - postgres
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
    networks:
      - nest_graphql_network
  postgres:
    image: postgres:lastest
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nest_graphql_network
    

volumes:
  postgres_data:
    driver: local
networks:
  nest_graphql_network:
    driver: bridge
    name: nest_graphql_network