version : "3.8"

services:
  email_subscription:
    container_name: email_subscription 
    build:
      context: .
      dockerfile: Dockerfile
    restart: always 
    ports: 
      - '${SERVER_PORT}:${SERVER_PORT}'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - docker.env
    depends_on:
      - postgres_docker
    networks:
      - postgres_networks

  postgres_docker: 
    container_name: email_postgres
    image: postgres:latest
    ports: 
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
    logging:
      driver: none
    networks:
      - postgres_networks

  pgadmin:
    links:
      - postgres_docker:postgres_docker
    container_name: email-pgadmin
    image: dpage/pgadmin4
    ports:
      - "8081:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    logging:
      driver: none
    networks:
      - postgres_networks


networks:
  postgres_networks:
    driver: bridge